sudo: false
language: node_js
node_js:
- 'lts/*'
env:
  global:
  - secure: D5/hJ1IdxVjlsixtKAdOPpfmEe4iFKwLj4/fz9eUSwx7bUF4glJf4Nr6nYqis2xy0IL604qzXxeH/RJotggVppYqbeRyqIsYzg23GxwsrM6SNoBTqOaGbkiqb928iMHZLr+B4h3WbAEjb8ERfeOVahykMwTbcgs4d2qmRLD57TRjJWPgNGGt85r0maMAG6vHberUhUNmVmJgqsrQcVG+Ho5gvsbDfWRRgbXkDDoX6JtoKeo+A93s8l+Q8cy1m/vFJnCRHv04+y9NLY0/dmfNiIzxSCfVsgEgxUmbFWf0cV58VZuSe1oo6rFxSrUe8UObhanGyAllKvWP+OOVhKyspP2iHG1+vt0i3jbbIjC20VM9EDn1qglKaIVuq6bE+2QfiOuTz06fv/AqHgE2UKw4pOnmuhUVjfgvf3y9rijn08cie5xWYK0/k1XH7vtjaaZTxRsFMu52rA8ZmnyqSV/Q07Sv1JJfv1sEyYzekf9KQJgnLg3sW6e+oOBx0irZwvazlNIV12TW+mKJoIw5iIi4G4WamcFUhyAwZHNyeH/PovVPsGSiBkKIxufgEWzt9Uodssl1MZsuHMUR8BsKgMLLza09kivHJjHK16OFaAwyGLYdDB5oq7JwG3cBnAGs8pYfD5IjXG/1YCnmTe0eC+Eqm1I0y7Iv94aCaXVMH/XlEMA=

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
