# Generated by Django 3.0.7 on 2020-06-17 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_relation_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='La demande est urgente')),
                ('exam_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'examen")),
                ('subject', models.CharField(max_length=50, verbose_name='Objet')),
                ('text_doctor', models.TextField(blank=True, verbose_name='Description du medecin')),
                ('text_expert', models.TextField(blank=True, verbose_name="Description de l'expert")),
                ('is_incomplete', models.BooleanField(default=False, verbose_name='Des informations complémentaire sont necessaire')),
                ('is_close', models.BooleanField(default=False, verbose_name='Le compte rendu est envoyé')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('solve_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi du rapprt")),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=254, upload_to='documents/%Y-%M-%D')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the file')),
                ('ext', models.CharField(max_length=10, verbose_name='extension du fichier')),
                ('is_answer', models.BooleanField(default=False, verbose_name='Est un document joint à une réponse')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Request')),
            ],
        ),
    ]
