# Generated by Django 3.0.7 on 2020-06-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_visited',
            field=models.BooleanField(default=False, verbose_name='Cette demande est déjà vue'),
        ),
    ]
