# Generated by Django 3.0.7 on 2020-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200618_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_visited',
        ),
        migrations.AddField(
            model_name='request',
            name='is_doctor_visited',
            field=models.BooleanField(default=True, verbose_name="Cette demande est vue par l'auteur "),
        ),
        migrations.AddField(
            model_name='request',
            name='is_expert_visited',
            field=models.BooleanField(default=False, verbose_name="Cette demande est vue par l'expert"),
        ),
    ]
