# Generated by Django 3.0.7 on 2020-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_request_is_doctor_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_doctor_visited',
            field=models.BooleanField(default=False, verbose_name="Cette demande est vue par l'auteur "),
        ),
    ]
