# Generated by Django 3.0.7 on 2020-06-20 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_request_is_doctor_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='solve_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi du rapprt"),
        ),
    ]
