# Generated by Django 3.0.8 on 2020-07-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20200620_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Le service est payé'),
        ),
    ]
