# Generated by Django 3.0.7 on 2020-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_send_email',
            field=models.BooleanField(default=True, verbose_name='Envoyer les nouvautés en email'),
        ),
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLIDAY', 'Holiday'), ('BUSY', 'Busy')], default='AVAILABLE', max_length=9, verbose_name='Status onligne'),
        ),
    ]
