# Generated by Django 3.0.7 on 2020-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200620_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_send_email',
            new_name='is_enable_mail',
        ),
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('HOLIDAY', 'Vacance'), ('BUSY', 'Occupé')], default='AVAILABLE', max_length=9, verbose_name='Status onligne'),
        ),
    ]
