# Generated by Django 3.0.7 on 2020-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200620_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_mail',
            field=models.BooleanField(default=True, verbose_name="L'email est verifié"),
        ),
    ]
