# Generated by Django 3.0.7 on 2020-06-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_verified_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_mail',
            field=models.BooleanField(default=False, verbose_name="L'email est verifié"),
        ),
    ]
